import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ClerkProvider, Show } from "@clerk/nextjs";
import { dark, neobrutalism } from "@clerk/ui/themes";
import { env } from "@/config/env.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Enso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          publishableKey={env.CLERK_PUBLISHABLE_KEY}
          appearance={{ theme: dark }}
          signInForceRedirectUrl="/tools"
          signUpForceRedirectUrl="/tools"
        >
          <Show when="signed-out">
            <Navbar />
          </Show>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
